# Generated by Django 5.2.8 on 2026-09-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactsubmission_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('services', models.TextField()),
                ('timeline', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True, default='')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
